### ISSUE TITLE
F2FS filesystem compatibility

### ISSUE THREAD

**Issue by sulisu** [ecdye/zram-config#100]
I have F2FS on my flash driver and zram-config failed to work. It seems that the code is hard coded to work with ext3 or ext4 filesystem.

I replaced this line in zram-config

```
mke2fs -v -t "$dirFSType" "/dev/zram${RAM_DEV}" &>> "$ZLOG" || return 1
```

with

```
	if [[ $dirFSType == "ext4" ]]; then
		mke2fs -v -t "$dirFSType" "/dev/zram${RAM_DEV}" &>> "$ZLOG" || return 1
	elif [[ $dirFSType == "f2fs" ]]; then
		mkfs.f2fs "/dev/zram${RAM_DEV}" &>> "$ZLOG" || return 1
	fi
```

Now it works.

**Comment by tux-ware** [comment]
Thanks for sharing how to add F2FS support.

**Comment by ecdye** [comment]
I like the idea behind this, but I would like to explore it more, and see if we could add support for any filesystem type by identifying it dynamically.
