### ISSUE TITLE
Remove cvt2f2fs

### ISSUE THREAD

**Issue by ecdye** [ecdye/zram-config#49]
@StuartIanNaylor Do you have a problem with me removing the `cvt2f2fs` files? I don't see any real point in keeping them as they are completely unrelated to this utility.

**Comment by StuartIanNaylor** [comment]
Yeah it was something I had forgotten about to be honest

**Comment by ecdye** [comment]
Sounds good, I just wanted to make sure.

**Comment by StuartIanNaylor** [comment]
I was wondering at one time if the file system could be loaded into overlayf/zram like the ephemeral mode and then convert a raspios file system to f2fs.
Totally forgot about it and not sure of the state of f2fs.
