### ISSUE TITLE
Five Minute Shutdown of Service 

### ISSUE THREAD

**Issue by BroMarduk** [ecdye/zram-config#51]
Using a new Buster 5.4.79 (December 2020) image.   
Default Lite image, with latest package updates.

Installed git package
Installed zram-config

No changes to ztab config file

If rebooting/shutting down , the shutdown hangs at "A stop job is running for zram-config (xxs / 5min)"

If stopping using sudo zram-config "stop" the hang occurs at: ` systemctl stop systemd-journald.socket systemd-journald-audit.socket systemd-journald-dev-log.socket` for about 5 minutes.

Is this normal behavior?  Am I missing some package in the Lite version?

**Comment by BroMarduk** [comment]
![20201216_214315](https://user-images.githubusercontent.com/2371774/102500998-ecd3e780-404a-11eb-89fc-f71fd5c3527c.jpg)

**Comment by ecdye** [comment]
Sort of, this is caused by the issues mentioned in the README relating to the systemd ordering dependencies. If it becomes an issue, you can manually stop zram-config before rebooting.
