### ISSUE TITLE
bad persistence on ZRAM

### ISSUE THREAD

**Issue by mstormi** [ecdye/zram-config#56]
just FYI, I ran into an extraordinarily mean error on my own production system that took me half a day to find out
(with shutters all down and heating off ☹️ ):

Some .rrd file (rrd4j persistent storage) was broken and that made Java crash repeatedly.
But deleting it didn't help. Persistence files are on ZRAM but seems when I deleted it ZRAM took the older version from the lowerFS and seems *that* was broken in the first place.
Duh.

No, don't know yet what to make of that, just documenting for now.

Maybe one thing is we should extend the permissions_corrections() apply to /opt/zram/*.bind/* too (the lowerFS copies of
all the ZRAM'ed dirs).

**Comment by ecdye** [comment]
This may have been caused by the improper sync of zram that was happening on shutdown until Sunday. I don't think it is a major issue.

**Comment by mstormi** [comment]
until Sunday ?
Are you aware that zram-config, unlike openhabian, does not get updated on every openhabian-config start ?
There (still) multiple reports of reboot to take very long or "fail".

**Comment by ecdye** [comment]
Yes I am aware. They need to update. See my comment of the other thread.

**Comment by mstormi** [comment]
ok let's close it given we assume with your fix and my permissions PR there's nothing left to do. We can reopen if I'm wrong here.
