### ISSUE TITLE
install.bash should cleanup after itself

### ISSUE THREAD

**Issue by bernstein82** [ecdye/zram-config#61]
just installing stuff with apt install and not cleaning up isn't very nice...

i suggest adding a `apt remove --auto-remove --purge git make gcc binutils cpp` step

**Comment by ecdye** [comment]
> i suggest adding a `apt remove --auto-remove --purge git make gcc binutils cpp` step

No, it is a very bad idea to do this as it would remove these packages if the user had installed them already. There is no reason to do this and it is very bad practice in a project to do so.
