### ISSUE TITLE
OpenRC init script

### ISSUE THREAD

**Issue by mjeveritt** [ecdye/zram-config#62]
Whilst systemd distros are definitely the dominant force in linux recently, there remain a few distros (Gentoo, Void, Artix, Adelie, Alpine, others) who still use Openrc (or others!) for their init system. Whilst I could make a crude attempt at an init script for these distros, I wonder whether the author is better placed to put something together appropriate to the application, taking into account the different feature-set that OpenRC has.
FWIW, any difficulties/queries with this, I can say that the #openrc support channel on Freenode IRC is quite responsive :smiley:

**Comment by ecdye** [comment]
As I don't personally use any distros that lack systemd, I have no real desire to implement an OpenRC script, if you would like to I would be happy to review it and include it in the project.
