### ISSUE TITLE
no longer works on ubuntu 21.10 (raspberry pi 4)

### ISSUE THREAD

**Issue by Mi-Sanchez** [ecdye/zram-config#71]
I had installed zram-config on ubuntu 21.04 (raspberry pi 4 - 4gb) and it worked beautifully.

After upgrading to ubuntu 21.10, zram-config unfortunately no longer works.
If I check the status of the service, it shows "failure".
I tried reinstalling zram-config but that didn't help either.

Can you help, please?

**Comment by ecdye** [comment]
I can't help unless you provide logging information to tell me what is happening on your system. All you have told me is that it does not work on ubuntu 21.10 but nothing about why it wasn't working. I am not a mind reader, I don't just know why X system does not work after an update. 

If you want any help at all, start by providing the full log located at `/usr/local/share/zram-config/log/zram-config.log` and then I might be able to understand why it might be failing.

**Comment by samlane-ma** [comment]
Similar issue here.  Apparently the zram kernel module for the Raspberry Pi has been moved to linux-modules-extra-raspi so this package will need to be installed on 21.10 and later to fix this.

**Comment by ecdye** [comment]
@samlane-ma Does b410aca fix the issue?

**Comment by samlane-ma** [comment]
I have just tried this on a fresh install (using Ubuntu Budgie 21.10 raspi).  I can confirm that it now works properly on 21.10.  Thank you.

**Comment by ThomasKaiser** [comment]
I ran into _similar_ issues right now with official Ubuntu Jammy 32-bit/armhf for Raspberry Pi and `zram-config` installer checked out from here today.

Rather sporadic behaviour: sometimes `/dev/zram1` missing, sometimes both zram devices. So I changed `/usr/local/sbin/zram-config`'s shebang line to `/bin/bash -x` and redirected all output into the log file: `exec 2>>"$ZLOG"`.

Attached one such log attempt:

    + [[ -z '' ]]
    + serviceConfiguration start
    + [[ start == \s\t\o\p ]]
    + [[ start == \s\t\a\r\t ]]
    + echo 'serviceConfiguration: Restarting services that interfere with zram device configuration.'
    serviceConfiguration: Restarting services that interfere with zram device configuration.
    + [[ -n '' ]]
    + [[ -n '' ]]
    + [[ -n '' ]]
    ++ grep -o '^ID=.*$' /etc/os-release
    ++ cut -d= -f2
    + OS=ubuntu
    + [[ -s /run/systemd/shutdown/scheduled ]]
    + case "$1" in
    + tee -a /usr/local/share/zram-config/log/zram-config.log
    ++ printf '%(%F-%T-%Z)T\n' -1
    + echo 'zram-config start 2022-04-22-13:38:30-UTC'
    zram-config start 2022-04-22-13:38:30-UTC
    + ZTAB_EMPTY=true
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + set -- swap lzo-rle 250M 750M 75 0 150
    + echo 'ztab create swap lzo-rle 250M 750M 75 0 150  '
    ztab create swap lzo-rle 250M 750M 75 0 150  
    + ZTAB_EMPTY=false
    + ZTYPE=swap
    + ALG=lzo-rle
    + MEM_SIZE=250M
    + DISK_SIZE=750M
    + [[ -s /tmp/zram-device-list ]]
    + case "$1" in
    + PRIORITY=75
    + PAGE_CLUSTER=0
    + SWAPPINESS=150
    + createZswap
    + echo 'createZswap: Beginning creation of zswap device.'
    createZswap: Beginning creation of zswap device.
    + createZdevice
    + echo 'createZdevice: Beginning creation of zDevice.'
    + [[ -d /sys/class/zram-control ]]
    + modprobe --verbose zram
    insmod /lib/modules/5.15.0-1005-raspi/kernel/drivers/block/zram/zram.ko 
    ++ zramctl --find --size 750M --algorithm lzo-rle
    ++ tr -dc 0-9
    zramctl: /dev/zram0: failed to reset: Device or resource busy
    + RAM_DEV=
    + [[ -z '' ]]
    + echo 'createZdevice: Failed to find an open zram device, trying one more time!'
    createZdevice: Failed to find an open zram device, trying one more time!
    ++ zramctl --find --size 750M --algorithm lzo-rle
    ++ tr -dc 0-9
    + RAM_DEV=0
    + [[ -z 0 ]]
    + echo 250M
    + [[ 250M == 0 ]]
    + echo 'createZdevice: zram0 created comp_algorithm=lzo-rle mem_limit=250M disksize=750M.'
    createZdevice: zram0 created comp_algorithm=lzo-rle mem_limit=250M disksize=750M.
    + mkswap --label zram-config0 /dev/zram0
    Setting up swapspace version 1, size = 750 MiB (786427904 bytes)
    LABEL=zram-config0, UUID=92c92dfc-1ea0-41e9-b67b-d149d91146c7
    + [[ -n 75 ]]
    + swapon -v -p 75 /dev/zram0
    swapon: /dev/zram0: found signature [pagesize=4096, signature=swap]
    swapon: /dev/zram0: pagesize=4096, swapsize=786432000, devsize=786432000
    swapon /dev/zram0
    + [[ -n 0 ]]
    + sysctl vm.page-cluster=0
    vm.page-cluster = 0
    + [[ -n 150 ]]
    + sysctl vm.swappiness=150
    vm.swappiness = 150
    + echo 'swap		/zram0		zram-config0'
    + echo 'createZswap: Completed zswap device creation.'
    createZswap: Completed zswap device creation.
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + continue
    + read -r line
    + case "$line" in
    + set -- log lzo-rle 50M 150M /var/log /opt/zram/log.bind /opt/zram/oldlog
    + echo 'ztab create log lzo-rle 50M 150M /var/log /opt/zram/log.bind /opt/zram/oldlog  '
    ztab create log lzo-rle 50M 150M /var/log /opt/zram/log.bind /opt/zram/oldlog  
    + ZTAB_EMPTY=false
    + ZTYPE=log
    + ALG=lzo-rle
    + MEM_SIZE=50M
    + DISK_SIZE=150M
    + [[ -s /tmp/zram-device-list ]]
    + [[ log == \s\w\a\p ]]
    ++ grep 'log.*/var/log' /tmp/zram-device-list
    + entry=
    + [[ -n '' ]]
    + case "$1" in
    + TARGET_DIR=/var/log
    + BIND_DIR=/opt/zram/log.bind
    + OLDLOG_DIR=/opt/zram/oldlog
    + serviceConfiguration stop
    + [[ stop == \s\t\o\p ]]
    + echo 'serviceConfiguration: Stopping services that interfere with zram device configuration.'
    serviceConfiguration: Stopping services that interfere with zram device configuration.
    + [[ ubuntu == \a\l\p\i\n\e ]]
    ++ systemctl is-active rsyslog.service
    + [[ active == \a\c\t\i\v\e ]]
    + export rsyslogActive=true
    + rsyslogActive=true
    + systemctl --no-block stop syslog.socket
    ++ systemctl is-active systemd-journald.service
    + [[ active == \a\c\t\i\v\e ]]
    + export journaldActive=true
    + journaldActive=true
    + journalctl --flush
    + systemctl --no-block stop systemd-journald.socket systemd-journald-audit.socket systemd-journald-dev-log.socket
    + createZdir
    + local dirPerm
    + local dirUser
    + local dirGroup
    + local dirMountOpt
    + local dirFSType
    + [[ -z /opt/zram/log.bind ]]
    + [[ -z /var/log ]]
    + echo 'createZdir: Beginning creation of /opt/zram/zram0.'
    createZdir: Beginning creation of /opt/zram/zram0.
    + mkdir -p /opt/zram/opt/zram/log.bind
    ++ stat -c %a /var/log
    + dirPerm=775
    ++ stat -c %u /var/log
    + dirUser=0
    ++ stat -c %g /var/log
    + dirGroup=111
    + echo 'createZdir: dirPerm - /var/log 775 0:111'
    createZdir: dirPerm - /var/log 775 0:111
    + mount --verbose --bind /var/log/ /opt/zram/opt/zram/log.bind/
    mount: /var/log bound on /opt/zram/opt/zram/log.bind.
    + mount --verbose --make-private /opt/zram/opt/zram/log.bind/
    mount: /opt/zram/opt/zram/log.bind propagation flags changed.
    ++ awk -v a=/opt/zram/opt/zram/log.bind '$2 == a {print $4}' /proc/mounts
    ++ head -1
    + dirMountOpt=rw,relatime,discard,errors=remount-ro
    ++ awk -v a=/opt/zram/opt/zram/log.bind '$2 == a {print $3}' /proc/mounts
    ++ head -1
    + dirFSType=ext4
    + echo 'createZdir: dirMountOpt - rw,relatime,discard,errors=remount-ro; dirFsType: ext4'
    createZdir: dirMountOpt - rw,relatime,discard,errors=remount-ro; dirFsType: ext4
    + createZdevice
    + echo 'createZdevice: Beginning creation of zDevice.'
    + [[ -d /sys/class/zram-control ]]
    ++ zramctl --find --size 150M --algorithm lzo-rle
    ++ tr -dc 0-9
    + RAM_DEV=1
    + [[ -z 1 ]]
    + echo 50M
    + [[ 50M == 0 ]]
    + echo 'createZdevice: zram1 created comp_algorithm=lzo-rle mem_limit=50M disksize=150M.'
    createZdevice: zram1 created comp_algorithm=lzo-rle mem_limit=50M disksize=150M.
    + mke2fs -v -t ext4 /dev/zram1
    mke2fs 1.46.5 (30-Dec-2021)
    fs_types for mke2fs.conf resolution: 'ext4', 'small'
    Discarding device blocks: done                            
    Filesystem label=
    OS type: Linux
    Block size=4096 (log=2)
    Fragment size=4096 (log=2)
    Stride=0 blocks, Stripe width=0 blocks
    38400 inodes, 38400 blocks
    1920 blocks (5.00%) reserved for the super user
    First data block=0
    Maximum filesystem blocks=39845888
    2 block groups
    32768 blocks per group, 32768 fragments per group
    19200 inodes per group
    Filesystem UUID: 01337964-2861-42e8-9235-52f725aedd51
    Superblock backups stored on blocks: 
    	32768
    
    Allocating group tables: done                            
    Writing inode tables: done                            
    Creating journal (4096 blocks): done
    Writing superblocks and filesystem accounting information: done
    
    + mkdir -p /opt/zram/zram1
    + mount --verbose --types ext4 -o rw,relatime,discard,errors=remount-ro /dev/zram1 /opt/zram/zram1/
    mount: /dev/zram1 mounted on /opt/zram/zram1.
    + mkdir -p /opt/zram/zram1/upper /opt/zram/zram1/workdir /var/log
    + mount --verbose --types overlay -o redirect_dir=on,lowerdir=/opt/zram/opt/zram/log.bind,upperdir=/opt/zram/zram1/upper,workdir=/opt/zram/zram1/workdir overlay1 /var/log
    mount: overlay1 mounted on /var/log.
    + chown 0:111 /opt/zram/zram1/upper /opt/zram/zram1/workdir /var/log
    + chmod 775 /opt/zram/zram1/upper /opt/zram/zram1/workdir /var/log
    + echo 'log		/zram1		/var/log		/opt/zram/log.bind'
    + [[ log == \l\o\g ]]
    + [[ -n /opt/zram/oldlog ]]
    + echo -e 'olddir /opt/zram/oldlog\ncreateolddir 755 root root\nrenamecopy'
    + echo 'createZdir: Creation of /opt/zram/zram1 complete.'
    createZdir: Creation of /opt/zram/zram1 complete.
    + read -r line
    + [[ false == \t\r\u\e ]]
    + [[ -z '' ]]
    + serviceConfiguration start
    + [[ start == \s\t\o\p ]]
    + [[ start == \s\t\a\r\t ]]
    + echo 'serviceConfiguration: Restarting services that interfere with zram device configuration.'
    serviceConfiguration: Restarting services that interfere with zram device configuration.
    + [[ -n true ]]
    + systemctl --no-block restart systemd-journald.socket systemd-journald-audit.socket systemd-journald-dev-log.socket
    + [[ -n true ]]
    + systemctl --no-block restart syslog.socket
    + [[ -n '' ]]

I stumbled about the `zramctl: /dev/zramX: failed to reset: Device or resource busy` messages and inserted a `sleep 0.2` prior to 2nd `zramctl --find` call in the `createZdevice` function.

10 reboots later it seems this works. Both zram devices as per default `/etc/ztab` were created.
